### ISSUE TITLE
0.6.0 doesn't work with Ktor 1.3

### ISSUE THREAD

**Issue by erikogenvik** [nielsfalk/ktor-swagger#51]
The signature of the io.ktor.client.call.TypeInfo class was changed in KTor 1.3, from
```
data class TypeInfo(val type: KClass<*>, val reifiedType: Type)
```
to
```
data class TypeInfo(
    val type: KClass<*>,
    val reifiedType: Type,
    val kotlinType: KType? = null
)
```

As a result, when running 0.6.0 on Ktor 1.3+ you will get this runtime error when calling anything which reads class metadata for Json:
```
java.lang.NoSuchMethodError: io.ktor.client.call.TypeInfo.<init>(Lkotlin/reflect/KClass;Ljava/lang/reflect/Type;)V
```

The solution would probably be to do a new release compiled against Ktor 1.3.

**Comment by devrimaksakal** [comment]
Version : 0.6.0 is not in maven repo. I tired with version: 0.5.0 and ktor:1.3.x and kotlin: 1.3.x. I get same error:
`java.lang.NoSuchMethodError: io.ktor.client.call.TypeInfo.<init>(Lkotlin/reflect/KClass;Ljava/lang/reflect/Type;)V`

Any plans on adressing the issue anytime soon?
Thanks in advance..

**Comment by jiaoling** [comment]
the master branch has updated the ktor and kotlin versions, but the author hasn't launched a new release yet. You could use the version `master-SNAPSHOT` to get the library working. Hopefully we could get a new release.

**Comment by JLLeitschuh** [comment]
Please open a pull request to resolve this issue if it's impacting you.
I'm no longer actively maintaining this project.
