### ISSUE TITLE
Not compatible with Ktor 1.3.*

### ISSUE THREAD

**Issue by jiaoling** [nielsfalk/ktor-swagger#49]
Hi,

i was working on a project with ktor 1.3.1, and would love to try out this swagger library, but i am getting this runtime error as below:

`java.lang.NoSuchMethodError: io.ktor.client.call.TypeInfo.<init>(Lkotlin/reflect/KClass;Ljava/lang/reflect/Type;)V`

the reason seems to be that since the Ktor migration to 1.3.0, it has a breaking change: No binary compatibility with 1.2.x. (See: https://ktor.io/quickstart/migration/1.3.0.html), so is it possible for you to recompile the project to the current Ktor version? Thanks!

**Comment by JLLeitschuh** [comment]
I welcome PRs to update the project. Unfortunately, I'm mostly in a 'I'll merge it if you submit it and write tests for it' stance currently.

**Comment by jiaoling** [comment]
Hi,
thanks for your reply, i just created a pull request to update the versions.
